### ISSUE TITLE
Costco Business Centers seem to cause some issues

### ISSUE THREAD

**Issue by deepcoder** [apsun/gastrak#1]
Hello,

First, thank you for your work to develop this tool.

I am a total noob here, still learning how to use your tool.

The Costco Business centers seem to add two extra fields in their record in the 'current.csv' file. So far I do not see this causing issues with downstream records. Just thought I would point it out as it causes the csv files to be a bit 'abby normal'. Example below.

Let me know if I can buy you a 🍺 or ☕️. Again, thx for your work!

```
      1 1665195962,420,Oxnard,34.224,-119.15,5.859,6.159,5.899
      2 1665195962,128,Simi Valley,34.283,-118.797,5.999,6.399,5.999
      3 1665195962,1205,Woodland Hills,34.187,-118.603,5.899,6.299,
      4 1665195962,437,Northridge,34.23,-118.554,5.899,6.299,
      5 1665195962,48,Van Nuys,34.182,-118.464,5.959,6.259,
      6 1665195962,1071,Pacoima,34.272,-118.428,5.899,6.359,
      7 1665195962,447,Santa Clarita,34.403,-118.46,5.999,6.499,
      8 1665195962,479,Culver City,33.991,-118.446,5.899,6.259,
      9 1665195962,677,Burbank,34.184,-118.323,5.999,6.399,
     10 1665195962,671,Hawthorne,33.899,-118.373,5.759,6.159,
     11 1665195962,769,Inglewood,33.945,-118.335,5.999,6.199,
     12 1665195962,564,Hawthorne Business Center,33.919,-118.343,5.759,6.159,5.559
     13 1665195962,1202,Torrance,33.808,-118.332,5.899,6.199,
     14 1665195962,428,Alhambra,34.088,-118.148,,6.299,
     15 1665195962,569,Commerce Business Center,33.995,-118.143,,6.199,
```

**Comment by apsun** [comment]
Sorry, can you clarify what exactly is wrong with those records? In case you're wondering about the two consecutive commas and trailing commas, that's just an empty field. Specifically those last 3 columns are [regular, premium, and diesel](https://github.com/apsun/gastrak/blob/master/data/gastrak.go#L163-L165) prices. If a field is empty, it means that the location doesn't carry gas of that type.

**Comment by deepcoder** [comment]
My mistake, apologies! My eyes don't do a good job with raw .csv files. I should not look at the output this way.

Thanks again for your work!
